apiVersion: v1
kind: Namespace
metadata:
  name: mcp-platform
  labels:
    name: mcp-platform
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mcp-platform-quota
  namespace: mcp-platform
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "10"
    services.loadbalancers: "2"
    services.nodeports: "10"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mcp-default-network-policy
  namespace: mcp-platform
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: mcp-platform
    - podSelector:
        matchLabels:
          mcp.server: "true"
  egress:
  - to:
    - namespaceSelector: {}
  - to:
    - podSelector: {}
  - ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53