apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-server-sa
  namespace: mcp-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mcp-server-role
  namespace: mcp-platform
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec", "pods/log"]
  verbs: ["get", "create"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mcp-server-rolebinding
  namespace: mcp-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mcp-server-role
subjects:
- kind: ServiceAccount
  name: mcp-server-sa
  namespace: mcp-platform
---
# Agent service accounts for accessing MCP servers
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-agent-sa
  namespace: mcp-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mcp-agent-role
  namespace: mcp-platform
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mcp-agent-rolebinding
  namespace: mcp-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mcp-agent-role
subjects:
- kind: ServiceAccount
  name: mcp-agent-sa
  namespace: mcp-platform