version: '3.8'

services:
  # Basic agent terminal service
  terminal-manager:
    build:
      context: ./services/terminal-manager
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=simple-secret-key
      - LOG_LEVEL=info
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - agent-terminal-net

  # Simple logging service
  log-streamer:
    build:
      context: ./services/log-streamer
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - agent-terminal-net

  # Web interface
  web-interface:
    build:
      context: ./web-interface
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
      - REACT_APP_WS_URL=ws://localhost:8081
    networks:
      - agent-terminal-net

  # Simple Redis for session storage
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - agent-terminal-net

volumes:
  redis-data:

networks:
  agent-terminal-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16